# Generated by Django 4.2.11 on 2024-04-11 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='bonas',
            new_name='bonus',
        ),
    ]
